In [20]:
#Cleaning data

import pandas as pd

df = pd.read_csv('/home/ksb/lumna/new.csv')

new_df = df.dropna()

print(new_df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  01/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    110       136     374.0  06/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60     98       123     275.0  14/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    102       126     334.5  24/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [21]:
import pandas as pd

df = pd.read_csv('/home/ksb/lumna/new.csv')

df.dropna(inplace = True)

print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  01/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    110       136     374.0  06/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60     98       123     275.0  14/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    102       126     334.5  24/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [22]:
import pandas as pd

df = pd.read_csv('/home/ksb/lumna/new.csv')

df.fillna(130, inplace = True) 
print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  01/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    110       136     374.0  06/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60     98       123     275.0  14/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112     130.0  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    102       126     334.5  24/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132     130.0  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [23]:
import pandas as pd

df = pd.read_csv('/home/ksb/lumna/new.csv')

df["Calories"].fillna(130, inplace = True)
print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  01/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    110       136     374.0  06/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60     98       123     275.0  14/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112     130.0  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    102       126     334.5  24/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132     130.0  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [24]:
import pandas as pd

df = pd.read_csv('/home/ksb/lumna/new.csv')

x = df["Calories"].mean()

df["Calories"].fillna(x, inplace = True) 
print(df.to_string())

    Duration  Pulse  Maxpulse    Calories        Date
0         60    110       130  409.100000  01/01/2015
1         60    117       145  479.000000  01/01/2015
2         60    103       135  340.000000  02/01/2015
3         45    109       175  282.400000  03/01/2015
4         45    117       148  406.000000  04/01/2015
5         60    102       127  300.000000  05/01/2015
6         60    110       136  374.000000  06/01/2015
7         45    104       134  253.300000  07/01/2015
8         30    109       133  195.100000  08/01/2015
9         60     98       124  269.000000  09/01/2015
10        60    103       147  329.300000  10/01/2015
11        60    100       120  250.700000  07/01/2015
12        60    106       128  345.300000  12/01/2015
13        60    104       132  379.300000  13/01/2015
14        60     98       123  275.000000  14/01/2015
15        60     98       120  215.200000  15/01/2015
16        60    100       120  300.000000  15/01/2015
17        45     90       112  306.061702  17/01/2015
18        60    103       123  323.000000  18/01/2015
19        45     97       125  243.000000  19/01/2015
20        60    108       131  364.200000  20/01/2015
21        45    100       119  282.000000  21/01/2015
22        60    130       101  300.000000  22/01/2015
23        45    105       132  246.000000  23/01/2015
24        60    102       126  334.500000  24/01/2015
25        60    100       120  250.000000  25/01/2015
26        60     92       118  241.000000  21/01/2015
27        60    103       132  306.061702  27/01/2015
28        60    100       132  280.000000  28/01/2015
29        60    102       129  380.300000  29/01/2015
30        60     92       115  243.000000  30/01/2015
31        45     90       112  180.100000  31/01/2015
32        60    101       124  299.000000  01/02/2015
33        60     93       113  223.000000  02/02/2015
34        60    107       136  361.000000  03/02/2015
35        60    114       140  415.000000  04/02/2015
36        60    102       127  300.000000  05/02/2015
37        60    100       120  300.000000  06/02/2015
38        60    100       120  300.000000  07/02/2015
39        45    104       129  266.000000  08/02/2015
40        45     90       112  180.100000  09/02/2015
41        60     98       126  286.000000  10/02/2015
42        60    100       122  329.400000  11/02/2015
43        60    111       138  400.000000  12/02/2015
44        60    111       131  397.000000  13/02/2015
45        60     99       119  273.000000  08/02/2015
46        60    109       153  387.600000  15/02/2015
47        45    111       136  300.000000  16/02/2015
48        45    108       129  298.000000  17/02/2015

In [25]:
import pandas as pd

df = pd.read_csv('/home/ksb/lumna/new.csv')

x = df["Calories"].median()

df["Calories"].fillna(x, inplace = True) 
print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  01/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    110       136     374.0  06/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60     98       123     275.0  14/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112     300.0  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    102       126     334.5  24/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132     300.0  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [27]:
import pandas as pd

df = pd.read_csv('/home/ksb/lumna/new.csv')

x = df["Calories"].mode()[0]

df["Calories"].fillna(x, inplace = True)
print(df.to_string())

    Duration  Pulse  Maxpulse  Calories        Date
0         60    110       130     409.1  01/01/2015
1         60    117       145     479.0  01/01/2015
2         60    103       135     340.0  02/01/2015
3         45    109       175     282.4  03/01/2015
4         45    117       148     406.0  04/01/2015
5         60    102       127     300.0  05/01/2015
6         60    110       136     374.0  06/01/2015
7         45    104       134     253.3  07/01/2015
8         30    109       133     195.1  08/01/2015
9         60     98       124     269.0  09/01/2015
10        60    103       147     329.3  10/01/2015
11        60    100       120     250.7  07/01/2015
12        60    106       128     345.3  12/01/2015
13        60    104       132     379.3  13/01/2015
14        60     98       123     275.0  14/01/2015
15        60     98       120     215.2  15/01/2015
16        60    100       120     300.0  15/01/2015
17        45     90       112     300.0  17/01/2015
18        60    103       123     323.0  18/01/2015
19        45     97       125     243.0  19/01/2015
20        60    108       131     364.2  20/01/2015
21        45    100       119     282.0  21/01/2015
22        60    130       101     300.0  22/01/2015
23        45    105       132     246.0  23/01/2015
24        60    102       126     334.5  24/01/2015
25        60    100       120     250.0  25/01/2015
26        60     92       118     241.0  21/01/2015
27        60    103       132     300.0  27/01/2015
28        60    100       132     280.0  28/01/2015
29        60    102       129     380.3  29/01/2015
30        60     92       115     243.0  30/01/2015
31        45     90       112     180.1  31/01/2015
32        60    101       124     299.0  01/02/2015
33        60     93       113     223.0  02/02/2015
34        60    107       136     361.0  03/02/2015
35        60    114       140     415.0  04/02/2015
36        60    102       127     300.0  05/02/2015
37        60    100       120     300.0  06/02/2015
38        60    100       120     300.0  07/02/2015
39        45    104       129     266.0  08/02/2015
40        45     90       112     180.1  09/02/2015
41        60     98       126     286.0  10/02/2015
42        60    100       122     329.4  11/02/2015
43        60    111       138     400.0  12/02/2015
44        60    111       131     397.0  13/02/2015
45        60     99       119     273.0  08/02/2015
46        60    109       153     387.6  15/02/2015
47        45    111       136     300.0  16/02/2015
48        45    108       129     298.0  17/02/2015

In [29]:
mport pandas as pd

df = pd.read_csv('data.csv')

print(df.duplicated())

ValueError: time data "13/01/2015" doesn't match format "%m/%d/%Y", at position 13. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.